spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:edwardpius/kind-argocd.git
    targetRevision: main

applications:
  - name: carts
  - name: catalog
  - name: checkout
  - name: orders
  - name: ui